document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id==='#')return;const el=document.querySelector(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'});}}));
const tipData={
getting:{title:"Getting Started",html:`<h4>Server Info</h4><p><b>EmpireZ : Star Wars : PvE with PvP Zones</b><br>IP Address: 64.20.63.70:2502</p><p><b>EmpireZ : Star Wars : PVP Raid</b><br>IP Address: 64.20.63.70:2302</p><h4>Update Mods</h4><ul><li>See announcements for what mods updated.</li><li>Type in the mod name.</li><li>Click the down arrow, then the 3 dots for that mod.</li><li>Click repair.</li></ul><h4>Commands</h4><p><b>!tips</b> — Links to all server tips categories<br><b>!clip</b> — Link to clipping software</p><h4>Other Tips</h4><ul><li>Use a wrench to flip your speeder.</li><li>Auto-Run feature available.</li><li>Main trader has limited items for purchase.</li><li>No PvP in the PVE area — DMG OFF.</li><li>Red circles on the map are PvP zones.</li><li>No building in military areas or POIs.</li><li>A buried stash lasts 14 days.</li><li>Press M in game and use the info tab for more details.</li><li>Storage/Tents/Walls/Crates last 7 days without a flag.</li></ul><p class="tip-note">Lost items: Admins cannot compensate lost items without proof. Take video clips.</p>`},
factions:{title:"Factions & Territories",html:`<ul><li>A flag kit must be placed and fully built within 7 days.</li><li>Flags cover a 60m radius.</li><li>1 flag per group.</li><li>Maximum group size: 15 players.</li><li>Sub groups are enabled.</li><li>Bases may only be taken over after the flag has fully despawned.</li><li>All door locks must also be despawned.</li><li>If unsure whether a base is clear, ask an admin before acting.</li><li>Flags automatically assign to your group when built.</li><li>Storage/Tents/Walls/Crates last 7 days without a flag.</li><li>A buried stash lasts 14 days.</li></ul>`},
traders:{title:"Traders",html:`<h4>Buy</h4><ul><li>Limited building supplies</li><li>BBP wallpapers & decor</li><li>Vehicles</li></ul><h4>Sell</h4><ul><li>Weapons</li><li>Artifacts</li></ul><h4>Important Notes</h4><ul><li>A map marker is available for “Limited Trader”.</li><li>Do not leave ships at trader when logging off.</li><li>Use one of the 3 garages at trader for proper ship storage.</li></ul>`},
events:{title:"World Events",html:`<ul><li><b>Jawa Crate — Tier 4:</b> notification plays and a map marker appears.</li><li><b>Krennic & Mando Ships:</b> random map spawns; more frequent in PvP zones; no announcement.</li><li><b>TIE Fighter Wrecks:</b> any tier; increased frequency in PvP zones.</li><li><b>Mando Safes:</b> Tier 3–4 military.</li><li><b>Loot Droids (Black):</b> Tier 3–4 military.</li><li><b>Loot Droids (Color):</b> any military tier.</li></ul>`},
force:{title:"Force Powers",html:`<p><i>Must be purchased in this order.</i></p><ul><li>Force Push — 10 Sith + 10 Jedi Medallions (F1)</li><li>Force Heal — 25 Sith + 25 Jedi Medallions (F3)</li><li>Force Shield — 35 Sith + 35 Jedi Medallions (F4)</li><li>Force Invisibility — 65 Sith + 65 Jedi Medallions (F10)</li><li>Force Jump — 75 Sith + 75 Jedi Medallions (F8)</li><li>Force Speed — 100 Sith + 100 Jedi Medallions (F7)</li></ul><p>Collect medallions, give them to the droid, and keep the receipt. Force powers apply after a restart.</p><p>A “True Sith” or “True Jedi” chat tag is added after all Force powers are acquired; open a ticket with proof of the last power.</p>`},
loot:{title:"Loot Tiers",html:`<h4>Tier 1–3</h4><p>Armor: Rebels, Clones, Stormtroopers, Bounty Hunters, Mandos, Smugglers, Tusken Raiders.<br>Weapons: x1–x2.</p><h4>Tier 3–4</h4><p>Weapons x3, Loot Droids, Mando Safes.</p><h4>Tier 4 — PvP Zones</h4><p>Rare armor variants, ammo x4, NBC filters/clothing, DC-15a + mags, E-5 + mags, DLT mags, 30-round mags, AKM, Commando backpacks, suppressors & ACOGs, M79/ASVAL, Mando crates, Loot Droids, extra TIE wrecks, Jawa crate loot, gold/chrome Mando parts, exclusive Level 2 clothing sets.</p><h4>Imperial Base</h4><p>Weapons x4, ammo x4, Kyber Crystals, Empty Datacards, Star Maps, Bunker Charges, Clone Commanders.</p><h4>Crash & Ship Loot</h4><p>TIE Fighter Wrecks can contain everything from water bottles to artifacts, weapons and valuables. Krennic Ship & Razorcrest can contain Empty Chain Code or Datapad.</p>`},
storage:{title:"Storage & Crafting",html:`<p>All custom storage containers hold <b>1,000 slots</b>. Exception: Wood Crate uses vanilla storage.</p><h4>Crafting Recipes</h4><ul><li>Han Storage — Han Carbonite + Hammer</li><li>Wood Crate — Planks + Nails</li><li>Locker — 10× Sheet Metal + 70× Nails</li><li>Gun Wall — 6× Sheet Metal + 70× Nails</li><li>Gear Stand — 1× Log + 70× Nails</li><li>All Other Storage — 2× Sheet Metal + box of Nails</li></ul>`},
artifact:{title:"Artifact Crafting",html:`<h4>Grey Order Saber</h4><ul><li>Yellow Kyber Crystal + Sword → Grey Order Lightsaber</li><li>Grey Order Lightsaber + Yellow Kyber Crystal → Overkill Grey Order Lightsaber</li></ul><h4>Swords</h4><ul><li>Black Kyber Crystal + Sword → Sith Warblade</li><li>Crimson Kyber Crystal + Crimson Nightsister Sword</li><li>Purple Kyber Crystal + Sword → Jedi Force Blade</li></ul><h4>Nightsister</h4><p>Nightsister Force Crystal + Mime Mask → Darth Maul Mask</p><h4>Vibroblades</h4><p>Pink Kyber Crystal + Machete → Vibroblade<br>Orange Kyber Crystal + Machete → Vibroblade</p><img class="artifact-guide" src="artifact-crafting.svg" alt="EmpireZ Elemental Crafting Recipes Part 1">`},
ships:{title:"Ships & Speeders",html:`<h4>Speeders</h4><p>Mini Speeder Bike • Endor Speeder Bike • Endor Speeder Bike (Red/Green/Blue) • Hover Bike • Bloodfin Speeder • Rey's Speeder • Solo StarWars Speeder (2 seater)</p><h4>Fighters & Small Ships</h4><p>TIE Fighter • TIE Interceptor • TIE Silencer • Royal TIE Fighter • Snow Speeder • Recon Speeder • Trident Fighter • X-Wing T-70 (OG/Teal/Red) • Partisan X-Wing • Black One • The Pink One • Scimitar • Soulless</p><h4>Transports</h4><p>FreckTransport • Imperial Shuttle</p><h4>LAAT Dropships</h4><p>LAAT Dropship Blue • Green • Black N White Partisan • Shock Battalion • 187th Infantry Battalion • Desert Camo</p>`},
quests:{title:"Quests",html:`<ul><li>Imperial Keycard → Opens Imperial Bunker</li><li>Ion Charge → Opens Hoth Bunker + Mando Bunker</li><li>Starmap (Red/Blue/Green) + Empty Data Card → Unlock Loot Droids</li><li>Chain Codes + Datapad → Unlock Mando Safes</li><li>Blue Kyber + Blue Kyber → Jedi Holocron → Jedi Hideout</li><li>Red Kyber + Red Kyber → Sith Holocron → Sith Temple</li><li>Green Kyber + Green Kyber → Nihilus Holocron → Mustafar Temple</li></ul>`}
};
const tipPanel=document.getElementById("tip-panel");
if(tipPanel){document.querySelectorAll(".tip-card").forEach(btn=>btn.addEventListener("click",()=>{const d=tipData[btn.dataset.tip];document.querySelectorAll(".tip-card").forEach(b=>b.classList.remove("active"));btn.classList.add("active");document.getElementById("tip-title").textContent=d.title;document.getElementById("tip-content").innerHTML=d.html;tipPanel.hidden=false;tipPanel.scrollIntoView({behavior:"smooth",block:"nearest"});}));document.querySelector(".tip-close").addEventListener("click",()=>{tipPanel.hidden=true;document.querySelectorAll(".tip-card").forEach(b=>b.classList.remove("active"));});}
